export const ADD_MY_FAVORITES = "ADD_MY_FAVORITES";
export const DELETE_MY_FAVORITES = "DELETE_MY_FAVORITES";
export const FILTER_MY_FAVORITES = "FILTER_MY_FAVORITES";
export const ORDER_MY_FAVORITES = "ORDER_MY_FAVORITES";
export const RESET_FILTERS = "RESET_FILTERS";
